import Head from 'next/head';
import { useState, useContext } from 'react';
import Image from 'next/image';

import Footer from '../components/Footer';
import Products from '../components/Products';
import Navbar from '../components/Navbar';
import Banner from '../components/Banner';
import ContextProvider from '../context/StateContext';
import { sanityClient, urlFor } from '../lib/sanity.server';
import { groq } from 'next-sanity';

export default function Home({ products, banner }) {
  const { iQty, dQty, qty } = useContext(ContextProvider);
  console.log(banner);

  return (
    <div className='index'>
      <Head>
        <title>GameGhorBD</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <Navbar />
        <Banner banner={banner} />
        {/* Button Render  */}
        <div className='flex gap-3 p-3 items-center'>
          <button
            className='bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow'
            onClick={iQty}
          >
            +
          </button>
          <span>{qty}</span>
          <button
            className='bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow'
            onClick={dQty}
          >
            -
          </button>
        </div>
        <Products />

        <Footer />
      </main>
    </div>
  );
}

export async function getStaticProps() {
  const products = await sanityClient.fetch(groq`*[_type == "product"]`);
  const banner = await sanityClient.fetch(groq`*[_type == "banner"]`);
  return {
    props: {
      products,
      banner,
    },
  };
}
